language: node_js

sudo: true

node_js:
  - "4.6.0"

cache:
  directories:
    - node_modules

notifications:
  email: false

script:
  - npm install -g react-native-cli
  - react-native init TextMoreDemo
  - cd TextMoreDemo
  - npm install react-native-textmore --save
  - react-native link
